GOOGLE_API_KEY = "AIzaSyAWrsppAxu_7wukeHFhVvmg8C0GrHu0v1U"
OPENAI_API_KEY = "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"
